// import 'package:flutter/material.dart';

// class LanguageService {
//   static const String english = 'en';
//   static const String vietnamese = 'vi';

//   static const List<String> supportedLocales = [english, vietnamese];

//   static final Map<String, Map<String, String>> _localizedValues = {
//     english: {
//       "@@locale": "en",
//       "settings": "Settings",
//       "language": "Language",
//       "selectAppLanguage": "Select app language",
//       "profileInfo": "Profile Information",
//       "logout": "Log out",
//       "courses": "Courses",
//       "learningGoals": "Learning Goals",
//       "theme": "Theme",
//       "sound": "Sound",
//       "notifications": "Notifications",
//       "support": "Support",
//       "about": "About",
//       "areYouSureLogout": "Are you sure you want to log out?",
//       "cancel": "Cancel",
//       "login": "Login",
//       "agree": "Agree",
//       "noAccount": "Don't have an account?",
//       "avatar": "Avatar",
//       "signup": "Sign up",
//       "or": "Or",
//       "username": "Username",
//       "enterYourEmail": "Enter your email",
//       "forgotPassword": "Forgot password?",
//       "loginName": "Login Name",
//       "password": "Password",
//       "email": "Email",
//       "deleteAccount": "Delete Account",
//       "addCourse": "Add Course",
//       "removeCourse": "Remove Course",
//       "goalsUnderDevelopment":
//           "Learning goals settings page (under development)",
//       "themeUnderDevelopment": "Theme settings page (under development)",
//       "soundUnderDevelopment": "Sound settings page (under development)",
//       "notificationsUnderDevelopment":
//           "Notifications settings page (under development)",
//       "supportUnderDevelopment": "Support page (under development)",
//       "aboutUnderDevelopment": "About page (under development)",
//       "support": "Support",
//       "developmentTeamInfo": "Development Team Information",
//       "contactSupport": "Contact Support",
//       "about": "About",
//       "introduction": "Introduction",
//       "developmentTeam": "Development Team",
//       "contact": "Contact",
//       "saveChanges": "Save Changes",
//       "deleteConfirmation":
//           "Are you sure you want to delete your account? This action cannot be undone.",
//       "notifications": "Notifications",
//       "courseNotifications": "Course Notifications",
//       "courseNotificationsDesc":
//           "Receive notifications about course progress and updates.",
//       "reminderNotifications": "Learning Reminders",
//       "reminderNotificationsDesc":
//           "Receive reminders to maintain your learning habit.",
//       "updateNotifications": "App Updates",
//       "updateNotificationsDesc":
//           "Receive notifications when a new version is available.",
//       "saveChanges": "Save Changes",
//       "theme": "Theme",
//       "selectTheme": "Select Theme",
//       "light": "Light",
//       "dark": "Dark",
//       "system": "System",
//       "themeSaved": "Theme settings saved",
//       "learningGoals": "Learning Goals",
//       "selectGoal": "Select Learning Goal",
//       "basic": "Basic",
//       "basicDesc": "Learn basic skills, suitable for beginners.",
//       "advanced": "Advanced",
//       "advancedDesc": "Develop in-depth skills, for those with a foundation.",
//       "expert": "Expert",
//       "expertDesc": "Achieve advanced proficiency, ideal for mastery.",
//       "continueButton": "Continue",
//       "goalTime": "Goal Completion Time",
//       "selectGoalTime": "Select Goal Completion Time",
//       "oneMonth": "1 Month",
//       "oneMonthDesc": "Complete your goal in a short, intensive period.",
//       "threeMonths": "3 Months",
//       "threeMonthsDesc": "A balanced pace to achieve your learning goal.",
//       "sixMonths": "6 Months",
//       "sixMonthsDesc": "A longer period for thorough mastery.",
//       "goalTimeSaved": "Goal completion time saved",
//       "studyTime": "Study Time",
//       "selectStudyTime": "Select Study Time",
//       "breakfast": "During Breakfast",
//       "commuting": "While Commuting",
//       "lunch": "During Lunch",
//       "dinner": "During Dinner",
//       "studyTimeSaved": "Study time saved",
//       "goalCompletion": "Goal Setup Complete",
//       "congratulations": "Congratulations!",
//       "goalSetSuccess": "You have successfully set your learning goal.",
//       "goalOverview": "Goal Overview",
//       "goalLabel": "Goal",
//       "timeLabel": "Completion Time",
//       "studyTimeLabel": "Study Time",
//       "finishButton": "Finish",
//       "activity": "Activity",
//       "activityOverview": "Activity Overview",
//       "studyTime": "Study Time",
//       "totalStudyTime": "Total Study Time",
//       "totalCourses": "Total Courses",
//       "courses": "courses",
//       "community": "Community",
//       "noPosts": "No posts yet",
//       "createPost": "Create Post",
//       "postTitle": "Title",
//       "postContent": "Content",
//       "submitPost": "Submit",
//       "likes": "Likes",
//       "comments": "Comments",
//       "addComment": "Add a comment"
//     },
//     vietnamese: {
//       "@@locale": "vi",
//       "settings": "Cài đặt",
//       "language": "Ngôn ngữ",
//       "selectAppLanguage": "Chọn ngôn ngữ ứng dụng",
//       "profileInfo": "Thông tin hồ sơ",
//       "logout": "Đăng xuất",
//       "courses": "Khóa học",
//       "learningGoals": "Mục tiêu học tập",
//       "theme": "Chủ đề",
//       "sound": "Âm thanh",
//       "notifications": "Thông báo",
//       "support": "Hỗ trợ",
//       "about": "Thông tin ứng dụng",
//       "areYouSureLogout": "Bạn có chắc muốn đăng xuất?",
//       "cancel": "Hủy",
//       "agree": "Đồng ý",
//       "avatar": "Ảnh đại diện",
//       "forgotPassword": "Quên mật khẩu?",
//       "username": "Tên người dùng",
//       "signup": "Đăng ký",
//       "or": "Hoặc",
//       "loginName": "Tên đăng nhập",
//       "password": "Mật khẩu",
//       "login": "Đăng nhập",
//       "email": "Email",
//       "deleteAccount": "Xóa tài khoản",
//       "enterYourEmail": "Nhập email của bạn",
//       "addCourse": "Thêm khóa học",
//       "removeCourse": "Xóa khóa học",
//       "goalsUnderDevelopment":
//           "Trang cài đặt mục tiêu học tập (đang phát triển)",
//       "themeUnderDevelopment": "Trang cài đặt chủ đề (đang phát triển)",
//       "soundUnderDevelopment": "Trang cài đặt âm thanh (đang phát triển)",
//       "notificationsUnderDevelopment":
//           "Trang cài đặt thông báo (đang phát triển)",
//       "supportUnderDevelopment": "Trang hỗ trợ (đang phát triển)",
//       "aboutUnderDevelopment": "Trang thông tin ứng dụng (đang phát triển)",
//       "noAccount": "Bạn chưa có tài khoản?",
//       "support": "Hỗ trợ",
//       "developmentTeamInfo": "Thông tin nhóm phát triển",
//       "contactSupport": "Liên hệ hỗ trợ",
//       "about": "Thông tin ứng dụng",
//       "introduction": "Giới thiệu",
//       "developmentTeam": "Nhóm phát triển",
//       "contact": "Liên hệ",
//       "saveChanges": "Lưu thay đổi",
//       "deleteConfirmation":
//           "Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác.",
//       "notifications": "Thông báo",
//       "courseNotifications": "Thông báo khóa học",
//       "courseNotificationsDesc":
//           "Nhận thông báo về tiến độ và cập nhật khóa học.",
//       "reminderNotifications": "Nhắc nhở học tập",
//       "reminderNotificationsDesc":
//           "Nhận nhắc nhở để duy trì thói quen học tập.",
//       "updateNotifications": "Cập nhật ứng dụng",
//       "updateNotificationsDesc": "Nhận thông báo khi có phiên bản mới.",
//       "saveChanges": "Lưu thay đổi",
//       "theme": "Giao diện",
//       "selectTheme": "Chọn giao diện",
//       "light": "Sáng",
//       "dark": "Tối",
//       "system": "Theo hệ thống",
//       "themeSaved": "Đã lưu cài đặt giao diện",
//       "learningGoals": "Mục tiêu học tập",
//       "selectGoal": "Chọn mục tiêu học tập",
//       "basic": "Cơ bản",
//       "basicDesc": "Học các kỹ năng cơ bản, phù hợp cho người mới bắt đầu.",
//       "advanced": "Nâng cao",
//       "advancedDesc":
//           "Phát triển kỹ năng chuyên sâu, dành cho người đã có nền tảng.",
//       "expert": "Chuyên gia",
//       "expertDesc": "Đạt trình độ cao cấp, phù hợp với người muốn thành thạo.",
//       "continueButton": "Tiếp tục",
//       "goalTime": "Thời gian hoàn thành mục tiêu",
//       "selectGoalTime": "Chọn thời gian hoàn thành mục tiêu",
//       "oneMonth": "1 tháng",
//       "oneMonthDesc": "Hoàn thành mục tiêu trong thời gian ngắn và tập trung.",
//       "threeMonths": "3 tháng",
//       "threeMonthsDesc": "Tiến độ cân bằng để đạt được mục tiêu học tập.",
//       "sixMonths": "6 tháng",
//       "sixMonthsDesc": "Thời gian dài hơn để thành thạo hoàn toàn.",
//       "goalTimeSaved": "Đã lưu thời gian hoàn thành mục tiêu",
//       "studyTime": "Thời gian học",
//       "selectStudyTime": "Chọn thời gian học",
//       "breakfast": "Khi ăn sáng",
//       "commuting": "Khi di chuyển",
//       "lunch": "Khi ăn trưa",
//       "dinner": "Khi ăn tối",
//       "studyTimeSaved": "Đã lưu thời gian học",
//       "goalCompletion": "Hoàn thành đặt mục tiêu",
//       "congratulations": "Chúc mừng!",
//       "goalSetSuccess": "Bạn đã đặt mục tiêu học tập thành công.",
//       "goalOverview": "Tổng quan mục tiêu",
//       "goalLabel": "Mục tiêu",
//       "timeLabel": "Thời gian hoàn thành",
//       "studyTimeLabel": "Thời gian học",
//       "finishButton": "Hoàn tất",
//       "activity": "Hoạt động",
//       "activityOverview": "Tổng quan hoạt động",
//       "studyTime": "Thời gian học",
//       "totalStudyTime": "Tổng thời gian học",
//       "totalCourses": "Tổng số khóa học",
//       "courses": "khóa học",
//       "community": "Cộng đồng học tập",
//       "noPosts": "Chưa có bài viết nào",
//       "createPost": "Viết bài",
//       "postTitle": "Tiêu đề",
//       "postContent": "Nội dung",
//       "submitPost": "Đăng bài",
//       "likes": "Lượt thích",
//       "comments": "Bình luận",
//       "addComment": "Thêm bình luận"
//     },
//   };

//   static String getTranslatedValue(BuildContext context, String key, {required Map<String, int> params}) {
//     final locale = Localizations.localeOf(context).languageCode;
//     return _localizedValues[locale]?[key] ?? _localizedValues[english]![key]!;
//   }

//   // Phương thức để lấy toàn bộ dữ liệu ngôn ngữ
//   static Map<String, String> getLanguageData(String languageCode) {
//     return _localizedValues[languageCode] ?? _localizedValues[english]!;
//   }
// }
Map<String, String> languageData = {
  "@@locale": "vi",
  "settings": "Cài đặt",
  "language": "Ngôn ngữ",
  "selectAppLanguage": "Chọn ngôn ngữ ứng dụng",
  "profileInfo": "Thông tin hồ sơ",
  "logout": "Đăng xuất",
  "courses": "Khóa học",
  "learningGoals": "Mục tiêu học tập",
  "theme": "Chủ đề",
  "sound": "Âm thanh",
  "notifications": "Thông báo",
  "support": "Hỗ trợ",
  "about": "Thông tin ứng dụng",
  "areYouSureLogout": "Bạn có chắc muốn đăng xuất?",
  "cancel": "Hủy",
  "agree": "Đồng ý",
  "avatar": "Ảnh đại diện",
  "forgotPassword": "Quên mật khẩu?",
  "username": "Tên người dùng",
  "signup": "Đăng ký",
  "or": "Hoặc",
  "loginName": "Tên đăng nhập",
  "password": "Mật khẩu",
  "login": "Đăng nhập",
  "email": "Email",
  "deleteAccount": "Xóa tài khoản",
  "enterYourEmail": "Nhập email của bạn",
  "addCourse": "Thêm khóa học",
  "removeCourse": "Xóa khóa học",
  "goalsUnderDevelopment": "Trang cài đặt mục tiêu học tập (đang phát triển)",
  "themeUnderDevelopment": "Trang cài đặt chủ đề (đang phát triển)",
  "soundUnderDevelopment": "Trang cài đặt âm thanh (đang phát triển)",
  "notificationsUnderDevelopment": "Trang cài đặt thông báo (đang phát triển)",
  "supportUnderDevelopment": "Trang hỗ trợ (đang phát triển)",
  "aboutUnderDevelopment": "Trang thông tin ứng dụng (đang phát triển)",
  "noAccount": "Bạn chưa có tài khoản?",
  "support": "Hỗ trợ",
  "developmentTeamInfo": "Thông tin nhóm phát triển",
  "contactSupport": "Liên hệ hỗ trợ",
  "about": "Thông tin ứng dụng",
  "introduction": "Giới thiệu",
  "developmentTeam": "Nhóm phát triển",
  "contact": "Liên hệ",
  "saveChanges": "Lưu thay đổi",
  "deleteConfirmation":
      "Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác.",
  "notifications": "Thông báo",
  "courseNotifications": "Thông báo khóa học",
  "courseNotificationsDesc": "Nhận thông báo về tiến độ và cập nhật khóa học.",
  "reminderNotifications": "Nhắc nhở học tập",
  "reminderNotificationsDesc": "Nhận nhắc nhở để duy trì thói quen học tập.",
  "updateNotifications": "Cập nhật ứng dụng",
  "updateNotificationsDesc": "Nhận thông báo khi có phiên bản mới.",
  "saveChanges": "Lưu thay đổi",
  "theme": "Giao diện",
  "selectTheme": "Chọn giao diện",
  "light": "Sáng",
  "dark": "Tối",
  "system": "Theo hệ thống",
  "themeSaved": "Đã lưu cài đặt giao diện",
  "learningGoals": "Mục tiêu học tập",
  "selectGoal": "Chọn mục tiêu học tập",
  "basic": "Cơ bản",
  "basicDesc": "Học các kỹ năng cơ bản, phù hợp cho người mới bắt đầu.",
  "advanced": "Nâng cao",
  "advancedDesc":
      "Phát triển kỹ năng chuyên sâu, dành cho người đã có nền tảng.",
  "expert": "Chuyên gia",
  "expertDesc": "Đạt trình độ cao cấp, phù hợp với người muốn thành thạo.",
  "continueButton": "Tiếp tục",
  "goalTime": "Thời gian hoàn thành mục tiêu",
  "selectGoalTime": "Chọn thời gian hoàn thành mục tiêu",
  "oneMonth": "1 tháng",
  "oneMonthDesc": "Hoàn thành mục tiêu trong thời gian ngắn và tập trung.",
  "threeMonths": "3 tháng",
  "threeMonthsDesc": "Tiến độ cân bằng để đạt được mục tiêu học tập.",
  "sixMonths": "6 tháng",
  "sixMonthsDesc": "Thời gian dài hơn để thành thạo hoàn toàn.",
  "goalTimeSaved": "Đã lưu thời gian hoàn thành mục tiêu",
  "studyTime": "Thời gian học",
  "selectStudyTime": "Chọn thời gian học",
  "breakfast": "Khi ăn sáng",
  "commuting": "Khi di chuyển",
  "lunch": "Khi ăn trưa",
  "dinner": "Khi ăn tối",
  "studyTimeSaved": "Đã lưu thời gian học",
  "goalCompletion": "Hoàn thành đặt mục tiêu",
  "congratulations": "Chúc mừng!",
  "goalSetSuccess": "Bạn đã đặt mục tiêu học tập thành công.",
  "goalOverview": "Tổng quan mục tiêu",
  "goalLabel": "Mục tiêu",
  "timeLabel": "Thời gian hoàn thành",
  "studyTimeLabel": "Thời gian học",
  "finishButton": "Hoàn tất",
  "activity": "Hoạt động",
  "activityOverview": "Tổng quan hoạt động",
  "studyTime": "Thời gian học",
  "totalStudyTime": "Tổng thời gian học",
  "totalCourses": "Tổng số khóa học",
  "courses": "khóa học",
  "community": "Cộng đồng học tập",
  "noPosts": "Chưa có bài viết nào",
  "createPost": "Viết bài",
  "postTitle": "Tiêu đề",
  "postContent": "Nội dung",
  "submitPost": "Đăng bài",
  "likes": "Lượt thích",
  "comments": "Bình luận",
  "addComment": "Thêm bình luận"
};
